# Generated by Django 6.1 on 2026-09-04 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmallChristianCommunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deaneries', to='members.diocese')),
            ],
        ),
        migrations.AddField(
            model_name='churchmember',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.family'),
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deanery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parishes', to='members.deanery')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='small_christian_community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='members.smallchristiancommunity'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='members.parish')),
            ],
        ),
        migrations.AddField(
            model_name='smallchristiancommunity',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='small_christian_communities', to='members.zone'),
        ),
        migrations.AddConstraint(
            model_name='deanery',
            constraint=models.UniqueConstraint(fields=('diocese', 'name'), name='unique_deanery_per_diocese'),
        ),
        migrations.AddConstraint(
            model_name='parish',
            constraint=models.UniqueConstraint(fields=('deanery', 'name'), name='unique_parish_per_deanery'),
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.UniqueConstraint(fields=('small_christian_community', 'name'), name='unique_family_per_scc'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('parish', 'name'), name='unique_zone_per_parish'),
        ),
        migrations.AddConstraint(
            model_name='smallchristiancommunity',
            constraint=models.UniqueConstraint(fields=('zone', 'name'), name='unique_scc_per_zone'),
        ),
    ]
