# Generated by Django 6.1 on 2026-10-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='baptism_certificate_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='spouse_digital_offering_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='spouse_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='spouse_is_catholic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='spouse_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='spouse_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='spouse_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
