# Generated by Django 6.1 on 2026-10-01 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_churchmember_baptism_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_member', to='members.churchmember'),
        ),
    ]
