# Generated by Django 6.1 on 2026-09-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_diocese_family_smallchristiancommunity_deanery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widow', 'Widow'), ('widower', 'Widower')], max_length=10),
        ),
    ]
