# Generated by Django 6.1 on 2026-09-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_churchmember_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchmember',
            name='family',
        ),
        migrations.AddField(
            model_name='churchmember',
            name='family_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
