# Generated by Django 6.1 on 2026-09-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_churchmember_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchmember',
            old_name='family_name',
            new_name='family',
        ),
    ]
