# Generated by Django 6.1 on 2026-10-07 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_churchmember_spouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_spouse_is_catholic', models.BooleanField(default=False)),
                ('proposed_spouse_digital_offering_number', models.CharField(blank=True, max_length=100)),
                ('proposed_spouse_first_name', models.CharField(blank=True, max_length=100)),
                ('proposed_spouse_middle_name', models.CharField(blank=True, max_length=100)),
                ('proposed_spouse_last_name', models.CharField(blank=True, max_length=100)),
                ('proposed_spouse_phone_number', models.CharField(blank=True, max_length=30)),
                ('proposed_marriage_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_marriage_requests', to=settings.AUTH_USER_MODEL)),
                ('church_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marriage_requests', to='members.churchmember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_marriage_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marriage Request',
                'verbose_name_plural': 'Marriage Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('church_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='members.churchmember')),
                ('current_scc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_requests', to='members.smallchristiancommunity')),
                ('destination_scc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_requests', to='members.smallchristiancommunity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer Request',
                'verbose_name_plural': 'Transfer Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelCertificateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_travel_certificate_requests', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_travel_certificate_requests', to=settings.AUTH_USER_MODEL)),
                ('church_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_certificate_requests', to='members.churchmember')),
            ],
            options={
                'verbose_name': 'Travel Certificate Request',
                'verbose_name_plural': 'Travel Certificate Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
